"""SQLite build target plus a Postgres seed emitter for Supabase."""

from __future__ import annotations

import sqlite3
from pathlib import Path

# Placeholder. Set when the embedding provider is chosen — see HANDOFF-allen.md.
EMBEDDING_DIM = 1536

TABLE_ORDER = (
    "sources",
    "brand_rebuttals",
    "lure_patterns",
    "reporting_contacts",
    "advisories",
    "message_examples",
    "kb_chunks",
)


def create_schema(conn: sqlite3.Connection, schema_path: Path) -> None:
    conn.executescript(schema_path.read_text(encoding="utf-8"))
    conn.commit()


def insert_rows(conn: sqlite3.Connection, table: str, rows: list[dict]) -> int:
    if not rows:
        return 0
    columns = list(rows[0].keys())
    placeholders = ", ".join("?" for _ in columns)
    statement = (
        f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})"
    )
    conn.executemany(statement, [tuple(r[c] for c in columns) for r in rows])
    conn.commit()
    return len(rows)


def _literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def emit_postgres_seed(
    conn: sqlite3.Connection, schema_path: Path, out_path: Path
) -> Path:
    """Write the Postgres schema followed by INSERTs for every row."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "-- Generated by build_kb.py. Do not edit by hand.",
        "-- Apply to Supabase: psql \"$SUPABASE_DB_URL\" -f kb_seed.postgres.sql",
        "",
        schema_path.read_text(encoding="utf-8"),
        "",
    ]
    boolean_columns = {"has_url", "retrievable", "eval_holdout"}
    for table in TABLE_ORDER:
        cursor = conn.execute(f"SELECT * FROM {table}")
        columns = [d[0] for d in cursor.description]
        rows = cursor.fetchall()
        if not rows:
            parts.append(f"-- {table}: no rows\n")
            continue
        parts.append(f"-- {table}: {len(rows)} rows")
        for row in rows:
            values = []
            for column, value in zip(columns, row):
                if column in boolean_columns and value is not None:
                    values.append("TRUE" if value else "FALSE")
                elif column == "embedding":
                    values.append("NULL")
                else:
                    values.append(_literal(value))
            parts.append(
                f"INSERT INTO {table} ({', '.join(columns)}) "
                f"VALUES ({', '.join(values)});"
            )
        parts.append("")
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    return out_path
